### ISSUE TITLE
Become official

### ISSUE THREAD

**Issue by mhils** [wernight/docker-mitmproxy#1]
Thanks for the great Dockerfile - would you be interested in making this the official mitmproxy image? I'd happily accept a PR that reduces our container size! :relaxed: 

(cc @dweinstein - he's our awesome chief Docker officer :smiley:)

**Comment by wernight** [comment]
Yes sure. On https://github.com/mitmproxy/mitmproxy I don't see your Dockerfile.

**Comment by dweinstein** [comment]
the base images are here https://github.com/mitmproxy/docker-base -- looks like the important changes are: use alpine as base, update some deps possibly for the dev base, and to use the mitmproxy user.

**Comment by bprashanth** [comment]
Thanks for dockerizing this. 

Why not upstream the python stuff as well? then people can use the same image to run `mitmdump -s` on a dump file

**Comment by wernight** [comment]
Moved to the official so closing this.
